[package]
name = "tic_tac_toe"
version = "0.1.0"
edition = "2021"
authors = ["Jezper Blixt <jezper.blixt@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
